[package]
name = "sheesh"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.0"
phf = { version = "0.11.1", features = ["macros"] }
subprocess = "0.2.9"